### Create new author
POST https://cse341-project2-8qt8.onrender.com/api/authors
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Austen",
  "bio": "English novelist known primarily for her six novels, which implicitly interpret, critique, and comment on the English landed gentry at the end of the 18th century.",
  "birthDate": "1997-08-25T00:00:00.000+00:00"
}

### Create another author
POST https://cse341-project2-8qt8.onrender.com/api/authors
Content-Type: application/json

{
  "firstName": "Dan",
  "lastName": "Brown",
  "bio": "An American author best known for his thriller novels, particularly the Robert Langdon series Angels & Demons, The Da Vinci Code, The Lost Symbol, Inferno, Origin and The Secret of Secrets.",
  "birthDate": "1964-06-22T00:00:00.000+00:00"
}

### Get all authors
GET https://cse341-project2-8qt8.onrender.com/api/authors

### Get author by id
GET https://cse341-project2-8qt8.onrender.com/api/authors/pasteidhere

### Update existing author by id
PUT https://cse341-project2-8qt8.onrender.com/api/authors/pasteidhere
Content-Type: application/json

{
  "birthDate": "1817-12-16T00:00:00.000+00:00"
}

### Delete author by id
DELETE https://cse341-project2-8qt8.onrender.com/api/authors/pasteidhere